Fix/update server validation types
marsidev/react-turnstile pull request #55
Opened 2024-02-17 17:45 UTC by jinsley8

### Description
Cloudflare returns extra properties not yet accounted for in `TurnstileServerValidationResponse` and the `error-codes` is always returned whether the validation is successful or not.

`messages` and `metadata` seem like they have been added to the response more recently but not yet documented in the [official server-side validation docs](https://developers.cloudflare.com/turnstile/get-started/server-side-validation/#accepted-parameters).

`metadata` is returned when validation is successful.

I am not quite sure of the purpose of `messages` so the comment isn't as detailed but it is only returned if validation fails.

### Changes Made
* Updated type for `error-codes` property so it is always required but can be an empty array.
* Added types for `messages` and `metadata`.

### Examples
<img width="365" alt="Screenshot 2024-02-16 at 11 52 00 PM" src="https://github.com/marsidev/react-turnstile/assets/5669143/000c58b0-7761-45d1-a50b-3d4a335412b0">

<img width="386" alt="Screenshot 2024-02-16 at 11 52 10 PM" src="https://github.com/marsidev/react-turnstile/assets/5669143/62083819-27f6-4737-a824-156e3636d8ec">

2024-02-18 15:53 UTC, marsidev requested changes
Can you please set `'error-codes': TurnstileServerValidationErrorCode[]`? That's a valid typing even for empty arrays.

2024-02-18 16:58 UTC, jinsley8 commented
@marsidev I've updated the `'error-codes'` type

2024-02-19 11:54 UTC, marsidev approved these changes

2024-02-19 11:54 UTC, merged

2024-02-19 11:54 UTC, marsidev commented
Thanks @jinsley8!